# Generated by Django 3.0.3 on 2020-12-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_status', models.CharField(choices=[('Bought', 'Bought'), ('Not Available', 'Not Available'), ('Pending', 'Pending')], max_length=60)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
